version: '3'
services:
  mysql_db:
    image: mysql:5.7.29
    restart: always
    ports:
      - 3306:3306
    env_file:
      - ./.mysql_db.env.dev
    # environment:
    #   MYSQL_DATABASE:
    #   MYSQL_USER:
    #   MYSQL_PASSWORD:
    #   MYSQL_ROOT_PASSWORD:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - /go/src/DockerGoNginx/api/vendor
      - ./api:/go/src/DockerGoNginx/api
    restart: always
    depends_on:
      - mysql_db
    env_file:
      - ./api/.env.dev
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql_db
      DB_PORT: 3306
      DB_DATABASE: kimigin
      DB_USERNAME: kimi
      DB_PASSWORD: 123456
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    depends_on:
      - api
    ports: 
      - '8080:80'