version: '3'
services:
  mysql:
    image: mysql:5.7.29
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env.dev
    environment:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - /go/src/DockerGoNginx/api/vendor
      - ./api:/go/src/DockerGoNginx/api
    restart: always
    depends_on:
      - mysql
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    depends_on:
      - api
    ports: 
      - '8080:80'